title: Western Carolina Waterscapes

description: >-
  Western Carolina Waterscapes is the premier pond and waterscape service in Western North Carolina. We specialize in pond maintenance, pond construction, and water feature installation with a unique specialization in Koi fish to take your pond to the next level.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://logan-morto.github.io" # or your custom domain later

collections:
  pages:
    output: true
    permalink: /:name/

business:
  email: "wcwaterscapes@gmail.com"
  phone: "+1 (919) 699-0897"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
